### ISSUE TITLE
是否有剧情文本和中英文剧情配音文件

### ISSUE THREAD

**Issue by Cai-z-us** [myssal/Reverse-1999-Assets#1]
是否有剧情文本和中英文剧情配音文件，想做点二创，谢谢大佬分享。
Do you have any drama texts and plot dubbing in Chinese or English? I want to make some second creation. Thanks for your share.

**Comment by myssal** [comment]
Thanks for opened issue, but I only extracted images so unfortunately no texts that I can share with you. Hope you can find them soon.
